---@class net_event # net_event object
---@field protocol_type number # protocol type
---@field proto_data string|nil # protobuff data
---@field message_id? integer # service uuid
---@field call_id? integer # local auto-increment ID, generated by the client or received call_id in the request
---@field method_id? integer # service method indexes
---@field error_id? integer # error code, in const.rpcerror
---@field err_msg? string # error message
---@field sub_type integer # serialized protobuf binary data
local net_event = {}


-- Create a new net_event object
---@param protocol_type number # protocol type
---@param proto_data string|nil # protobuff data
---@return net_event # net_event object with protocol type and protobuff
function net_event:new(protocol_type, proto_data)
    local ne = {
        protocol_type = protocol_type,
        proto_data = proto_data
    }
    self.__index = self
    setmetatable(ne, self)
    return ne
end

return net_event
